name: Docker Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker images
      run: docker-compose build

    - name: Run the Docker containers
      run: |
        docker-compose up -d
        sleep 10  # Give containers time to start

    - name: Check running containers
      run: docker-compose ps

    - name: Check container logs
      run: |
        docker-compose logs ticketsystem.api
        docker-compose logs ticketsystem.ui
        docker-compose logs nginx

    - name: Test API Swagger
      run: |
        curl -f http://localhost:8080/api/swagger || exit 1

    - name: Cleanup
      run: docker-compose down